### ISSUE TITLE
libjpgt.so找不到您知道是为什么吗

### ISSUE THREAD

**Issue by yuanze18** [simplezhli/Tesseract-OCR-Scanner#9]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libjpgt.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.googlecode.tesseract.android.TessBaseAPI.<clinit>(TessBaseAPI.java:49)
        at com.baidu.speech.recognizerdemo.scanner.tess.TessEngine.detectText(TessEngine.java:27)
        at com.baidu.speech.recognizerdemo.scanner.decode.DecodeHandler.decode(DecodeHandler.java:126)
        at com.baidu.speech.recognizerdemo.scanner.decode.DecodeHandler.handleMessage(DecodeHandler.java:65)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at com.baidu.speech.recognizerdemo.scanner.decode.DecodeThread.run(DecodeThread.java:52)

**Comment by simplezhli** [comment]
@yuanze18 尝试参考 https://github.com/rmtheis/tess-two/issues/150#issuecomment-232864508

**Comment by yuanze18** [comment]
感谢

**Comment by yuanze18** [comment]
拍照识别的照片 总是逆时针旋转了，并且跟预览框位置是错位的，这个有办法解决吗

**Comment by simplezhli** [comment]
部分手机存在这类旋转现象，需要获取图片旋转角度后旋转图片修正。
至于错位问题之前我也发现了，应该是哪里的计算疏漏了。有时间我会定位一下。

**Comment by yuanze18** [comment]
好的，我的是一加8
